SELECT * FROM CUSTOMERS
SELECT * FROM MERCHANTS
SELECT * FROM REFUNDS
SELECT * FROM RISK_FRAUD
SELECT * FROM TRANSACTIONS



-- Q 1 TOTAL TRANSACTIONS AND TRANSACTION VALUE

SELECT COUNT(DISTINCT TRANSACTION_ID) AS TOTAL_TRANSACTION,
SUM(TRANSACTION_AMOUNT) AS TOTAL_AMOUNT
FROM TRANSACTIONS

-- Q 2 AVERAGE TRANSACTION AMOUNT

SELECT AVG(TRANSACTION_AMOUNT) AS AVG_TRANSACTION_AMOUNT
FROM TRANSACTIONS

-- Q 3 YEAR WISE TRANSACTION AMOUNT AND TOTAL TRANSACTION

SELECT EXTRACT(YEAR FROM TRANSACTION_DATE) AS YEAR,
COUNT(DISTINCT TRANSACTION_ID) AS TOTAL_TRANSACTIONS,
SUM(TRANSACTION_AMOUNT) AS TOTAL_TRANSACTION_AMOUNT
FROM TRANSACTIONS
GROUP BY YEAR
ORDER BY YEAR

-- Q4 MONTH WISE TRANSACTIONS

SELECT EXTRACT(MONTH FROM TRANSACTION_DATE) AS MONTH,
COUNT(DISTINCT TRANSACTION_ID) AS TOTAL_TRANSACTIONS
FROM TRANSACTIONS
GROUP BY MONTH
ORDER BY MONTH

-- Q 5 HIGH VALUE TRANSACTIONS

SELECT TRANSACTION_ID, CUSTOMER_ID, TRANSACTION_AMOUNT
FROM TRANSACTIONS
ORDER BY TRANSACTION_AMOUNT DESC
LIMIT 10


-- Q 6 TRANSACTION STATUS BREAKDOWN

SELECT TRANSACTION_STATUS AS STATUS,
COUNT(DISTINCT TRANSACTION_ID) AS TOTAL_TRANSACTIONS
FROM TRANSACTIONS
GROUP BY STATUS
ORDER BY TOTAL_TRANSACTIONS DESC

-- Q 7 PAYMENT METHOD WISE TRANSACTIONS

SELECT PAYMENT_METHOD,
COUNT(DISTINCT TRANSACTION_ID) AS TOTAL_TRANSACTIONS
FROM TRANSACTIONS
GROUP BY PAYMENT_METHOD
ORDER BY TOTAL_TRANSACTIONS

-- Q 8 PAYMENT METHOD WISE TOTAL TRANSACTION AMOUNT

SELECT PAYMENT_METHOD,
SUM(TRANSACTION_AMOUNT) AS TOTAL_TRANSACTIONS_AMOUNT
FROM TRANSACTIONS
GROUP BY PAYMENT_METHOD
ORDER BY TOTAL_TRANSACTIONS_AMOUNT

-- Q 9  PAYMENT METHOD WISE AVERAGE TRANSACTION AMOUNT

SELECT PAYMENT_METHOD,
AVG(TRANSACTION_AMOUNT) AS AVG_TRANSACTIONS_AMOUNT
FROM TRANSACTIONS
GROUP BY PAYMENT_METHOD
ORDER BY AVG_TRANSACTIONS_AMOUNT

-- Q 10 FAILURE AND DECLINED VALUES

SELECT PAYMENT_METHOD, TRANSACTION_STATUS,
COUNT(DISTINCT TRANSACTION_ID) AS TOTAL_TRANSACTIONS
FROM TRANSACTIONS
WHERE TRANSACTION_STATUS IN ('Failed', 'Declined')
GROUP BY PAYMENT_METHOD, TRANSACTION_STATUS
ORDER BY TOTAL_TRANSACTIONS DESC


-- Q 11 CHANNEL WISE TRANSACTIONS

SELECT CHANNEL, COUNT(TRANSACTION_ID) AS 
TOTAL_TRANSACTION
FROM TRANSACTIONS
GROUP BY CHANNEL
ORDER BY TOTAL_TRANSACTION DESC

-- Q 12 CHANNEL WISE TRANSACTION AMOUNT

SELECT CHANNEL, SUM(TRANSACTION_AMOUNT) AS 
TOTAL_TRANSACTION_AMOUNT
FROM TRANSACTIONS
GROUP BY CHANNEL
ORDER BY TOTAL_TRANSACTION_AMOUNT DESC

-- Q 13 CHANNEL WISE FAILED AND DECLINED TRANSACTIONS

SELECT CHANNEL, TRANSACTION_STATUS,
COUNT(DISTINCT TRANSACTION_ID) AS TOTAL_TRANSACTION
FROM TRANSACTIONS
WHERE TRANSACTION_STATUS IN ('Failed', 'Declined')
GROUP BY CHANNEL, TRANSACTION_STATUS
ORDER BY TOTAL_TRANSACTION DESC


-- Q 14 CUSTOMER SEGMENT WISE TRANSACTION AMOUNT

SELECT C.CUSTOMER_SEGMENT, SUM(T.TRANSACTION_AMOUNT) AS TOTAL_AMOUNT
FROM TRANSACTIONS T
JOIN
CUSTOMERS C
ON T.CUSTOMER_ID = C.CUSTOMER_ID
GROUP BY C.CUSTOMER_SEGMENT
ORDER BY TOTAL_AMOUNT DESC

-- Q 15 ACCOUNT TYPE WISE TRANSACTION AMOUNT

SELECT C.ACCOUNT_TYPE, SUM(T.TRANSACTION_AMOUNT) AS TOTAL_AMOUNT
FROM TRANSACTIONS T
JOIN
CUSTOMERS C
ON T.CUSTOMER_ID = C.CUSTOMER_ID
GROUP BY C.ACCOUNT_TYPE
ORDER BY TOTAL_AMOUNT DESC


-- Q 16 STATE WISE TRANSACTION AMOUNT

SELECT C.STATE, SUM(T.TRANSACTION_AMOUNT) AS TOTAL_AMOUNT
FROM TRANSACTIONS T
JOIN
CUSTOMERS C
ON T.CUSTOMER_ID = C.CUSTOMER_ID
GROUP BY C.STATE
ORDER BY TOTAL_AMOUNT DESC


-- Q 17 TOP 10 CUSTOMERS BY TRANSACTION AMOUNT

SELECT C.CUSTOMER_ID, SUM(T.TRANSACTION_AMOUNT) AS TOTAL_AMOUNT
FROM TRANSACTIONS T
JOIN
CUSTOMERS C
ON T.CUSTOMER_ID = C.CUSTOMER_ID
GROUP BY C.CUSTOMER_ID
ORDER BY TOTAL_AMOUNT DESC
LIMIT 10


-- Q 18 TOP 10 CUSTOMERS BY TRANSACTIONS

SELECT C.CUSTOMER_ID, COUNT(DISTINCT T.TRANSACTION_ID) AS TOTAL_TRANSACTIONS
FROM TRANSACTIONS T
JOIN
CUSTOMERS C
ON T.CUSTOMER_ID = C.CUSTOMER_ID
GROUP BY C.CUSTOMER_ID
ORDER BY TOTAL_TRANSACTIONS DESC
LIMIT 10


-- Q 19 MOST TRANSACTION ACTIVITY CUSTOMER SEGMENT

SELECT C.CUSTOMER_SEGMENT,
COUNT(DISTINCT C.CUSTOMER_ID) AS TOTAL_CUSTOMER,
COUNT(DISTINCT T.TRANSACTION_ID) AS TOTAL_TRANSACTIONS
FROM TRANSACTIONS T
JOIN
CUSTOMERS C
ON T.CUSTOMER_ID = C.CUSTOMER_ID
GROUP BY C.CUSTOMER_SEGMENT
ORDER BY TOTAL_TRANSACTIONS DESC


-- Q 20 MARCHANTS CATEGORY WISE AMOUNT

SELECT M.Merchant_Category,
SUM(T.TRANSACTION_AMOUNT) AS TOTAL_AMOUNT
FROM TRANSACTIONS T
JOIN
MERCHANTS M
ON T.MERCHANT_ID = M.MERCHANT_ID
GROUP BY M.Merchant_Category
ORDER BY TOTAL_AMOUNT DESC


-- Q 21 MERCHANT CATEGORY WISE TRANSACTIONS

SELECT M.MERCHANT_CATEGORY,
COUNT(DISTINCT T.TRANSACTION_ID) AS TOTAL_TRANSACTIONS
FROM TRANSACTIONS T
JOIN MERCHANTS M
ON T.MERCHANT_ID = M.MERCHANT_ID
GROUP BY M.MERCHANT_CATEGORY
ORDER BY TOTAL_TRANSACTIONS DESC


-- Q 22 TOP 10 MERCHANTS BY AMOUNT

SELECT M.MERCHANT_ID, SUM(T.TRANSACTION_AMOUNT) AS TOTAL_AMOUNT
FROM TRANSACTIONS T
join
MERCHANTS M
ON T.MERCHANT_ID = M.MERCHANT_ID
GROUP BY M.MERCHANT_ID
ORDER BY TOTAL_AMOUNT DESC
LIMIT 10


-- Q 23 MERCHANT CATEGORY WISE FAILED AND DECLINED TRANSACTIONS


SELECT M.MERCHANT_CATEGORY, T.TRANSACTION_STATUS,
COUNT(DISTINCT T.TRANSACTION_ID) AS TOTAL_TRANSACTIONS
FROM TRANSACTIONS T
JOIN
MERCHANTS M
ON T.MERCHANT_ID = M.MERCHANT_ID
WHERE TRANSACTION_STATUS IN ('Failed', 'Declined')
GROUP BY M.MERCHANT_CATEGORY, T.TRANSACTION_STATUS
ORDER BY TOTAL_TRANSACTIONS DESC


-- Q 24 TOATL AND AVG TRANSACTION FEE

SELECT SUM(TRANSACTION_FEE) AS TOTAL_FEE,
AVG(TRANSACTION_FEE) AS AVG_FEE
FROM TRANSACTIONS


-- Q 25 PAYMENT METHOD WISE TRANSACTION FEE

SELECT PAYMENT_METHOD,
SUM(TRANSACTION_FEE) AS TOTAL_FEE
FROM TRANSACTIONS
GROUP BY PAYMENT_METHOD
ORDER BY TOTAL_FEE DESC


-- Q 26 TOTAL REFUND AMOUNT AND VALUES

SELECT COUNT(DISTINCT REFUND_ID) AS TOTAL_REFUND,
SUM(REFUND_AMOUNT) AS TOTAL_REFUND_AMOUNT
FROM REFUNDS


-- Q 27 REFUND STATUS WISE REFUNDS AND REFUND AMOUNT

SELECT REFUND_STATUS, COUNT(DISTINCT REFUND_ID) AS TOTAL_REFUND,
SUM(REFUND_AMOUNT) AS TOTAL_REFUND_AMOUNT
FROM REFUNDS
GROUP BY REFUND_STATUS


-- Q 28 (A) PAYMENT METHOD WISE REFUND

SELECT T.PAYMENT_METHOD, 
SUM(R.REFUND_AMOUNT) AS TOTAL_REFUND_AMOUNT
FROM REFUNDS R
JOIN TRANSACTIONS T
ON R.TRANSACTION_ID = T.TRANSACTION_ID
GROUP BY T.PAYMENT_METHOD
ORDER BY TOTAL_REFUND_AMOUNT DESC

-- (B) MERCHANT CATEGORY WISE REFUND

SELECT M.MERCHANT_CATEGORY, 
SUM(R.REFUND_AMOUNT) AS TOTAL_REFUND_AMOUNT
FROM REFUNDS R
JOIN TRANSACTIONS T
ON R.TRANSACTION_ID = T.TRANSACTION_ID
JOIN MERCHANTS M
ON T.MERCHANT_ID = M.MERCHANT_ID
GROUP BY M.MERCHANT_CATEGORY
ORDER BY TOTAL_REFUND_AMOUNT DESC


-- Q 29 TOTAL FRAUD

SELECT COUNT(Transaction_ID) AS TOTAL_FRAUD
FROM RISK_FRAUD
WHERE FRAUD_FLAG = 'Yes';


-- Q 30 Overall Fraud Pattern Analysis

SELECT T.PAYMENT_METHOD, T.CHANNEL, M.MERCHANT_CATEGORY, R.RISK_LEVEL,
COUNT(R.TRANSACTION_ID) AS TOTAL_FRAUD
FROM RISK_FRAUD R
JOIN TRANSACTIONS T
ON R.TRANSACTION_ID = T.TRANSACTION_ID
JOIN MERCHANTS M
ON T.MERCHANT_ID = M.MERCHANT_ID
WHERE R.FRAUD_FLAG = 'Yes'
GROUP BY T.PAYMENT_METHOD, T.CHANNEL, M.MERCHANT_CATEGORY, R.RISK_LEVEL
ORDER BY TOTAL_FRAUD DESC;